### ISSUE TITLE
baseimg == NULL error spam

### ISSUE THREAD

**Issue by Zughy** [mt-mods/signs_lib#33]
Joining A.E.S. server (5.8.0) on 5.9.0/5.10-dev. We had no issues with 5.8 clients (can't bother to downgrade but it should work fine still)

![image](https://github.com/user-attachments/assets/b70c08ee-9f6b-4884-85f2-4f1953dd0f37)

It might be signs_lib, since grepping for the colours in the screenshot produces no value (in our mods folder) and since it seems to spam more when I reach blocks having signs inside? Or maybe it's not and in case sorry for bothering.

We've also updated to latest master, no luck

**Comment by BuckarooBanzay** [comment]
i'm not so sure this comes from the `signs_lib` mod: i grep'ed for the string "multiply" and this is the only thing i could find:

```
signs_lib$ grep "multiply" . -Rn
./api.lua:1302:			local pos1 = vector.multiply(blockpos, minetest.MAP_BLOCKSIZE)
```

(not really relevant for the formspec building)

**Comment by Zughy** [comment]
After going deeper, it was another mod indeed, sorry!
